// patientsData.ts
export interface Patient {
    name: string;
    patient_no: string;
    patient_contact: string;
    patient_type: string;
    doctor_name: string;
    bill_no: string;
    bill_date: string;
    bill_amount: string;
    total_amount: string;
    payment_status: string;
    payment_date: string;
    payment_mode: string;
    payment_receipt: string;
    test_status: string;
  }
  

  export const patients: Patient[] = [
    {
      name: "Jane Cooper",
      patient_no: "12",
      patient_contact: "1234567890",
      patient_type: "IP",
      doctor_name: "Dr. Arjun",
      bill_no: "123456",
      bill_date: "2021-01-21",
      bill_amount: "123456",
      total_amount: "3000",
      payment_status: "Paid",
      payment_date: "2021-01-21",
      payment_mode: "Cash",
      payment_receipt: "123456",
      test_status: "Pending",
    },
    {
      name: "John Smith",
      patient_no: "13",
      patient_contact: "987654",
      patient_type: "OP",
      doctor_name: "Dr. Riya",
      bill_no: "123457",
      bill_date: "2021-02-15",
      bill_amount: "5000",
      total_amount: "5000",
      payment_status: "Paid",
      payment_date: "2021-02-16",
      payment_mode: "Credit Card",
      payment_receipt: "123457",
      test_status: "Completed",
    },
    {
      name: "Emily Johnson",
      patient_no: "14",
      patient_contact: "456789",
      patient_type: "IP",
      doctor_name: "Dr. Mohan",
      bill_no: "123458",
      bill_date: "2021-03-01",
      bill_amount: "7500",
      total_amount: "7500",
      payment_status: "Pending",
      payment_date: "",
      payment_mode: "",
      payment_receipt: "",
      test_status: "Pending",
    },
    {
      name: "Michael Brown",
      patient_no: "15",
      patient_contact: "321654",
      patient_type: "OP",
      doctor_name: "Dr. Kavita",
      bill_no: "123459",
      bill_date: "2021-03-10",
      bill_amount: "3000",
      total_amount: "3000",
      payment_status: "Paid",
      payment_date: "2021-03-11",
      payment_mode: "Debit Card",
      payment_receipt: "123459",
      test_status: "Completed",
    },
    {
      name: "Olivia Davis",
      patient_no: "16",
      patient_contact: "654321",
      patient_type: "IP",
      doctor_name: "Dr. Rajesh",
      bill_no: "123460",
      bill_date: "2021-04-05",
      bill_amount: "15000",
      total_amount: "15000",
      payment_status: "Paid",
      payment_date: "2021-04-06",
      payment_mode: "Cash",
      payment_receipt: "123460",
      test_status: "Completed",
    },
    {
      name: "Sophia Wilson",
      patient_no: "17",
      patient_contact: "159753",
      patient_type: "OP",
      doctor_name: "Dr. Anil",
      bill_no: "123461",
      bill_date: "2021-05-12",
      bill_amount: "2000",
      total_amount: "2000",
      payment_status: "Paid",
      payment_date: "2021-05-13",
      payment_mode: "Net Banking",
      payment_receipt: "123461",
      test_status: "Completed",
    },
    {
      name: "Liam Miller",
      patient_no: "18",
      patient_contact: "753159",
      patient_type: "IP",
      doctor_name: "Dr. Neha",
      bill_no: "123462",
      bill_date: "2021-06-20",
      bill_amount: "12000",
      total_amount: "12000",
      payment_status: "Pending",
      payment_date: "",
      payment_mode: "",
      payment_receipt: "",
      test_status: "Pending",
    },
    {
      name: "Ava Garcia",
      patient_no: "19",
      patient_contact: "258963",
      patient_type: "OP",
      doctor_name: "Dr. Suresh",
      bill_no: "123463",
      bill_date: "2021-07-15",
      bill_amount: "3500",
      total_amount: "3500",
      payment_status: "Paid",
      payment_date: "2021-07-16",
      payment_mode: "Cash",
      payment_receipt: "123463",
      test_status: "Completed",
    },
    {
      name: "Noah Rodriguez",
      patient_no: "20",
      patient_contact: "369258",
      patient_type: "IP",
      doctor_name: "Dr. Priya",
      bill_no: "123464",
      bill_date: "2021-08-25",
      bill_amount: "9000",
      total_amount: "9000",
      payment_status: "Paid",
      payment_date: "2021-08-26",
      payment_mode: "Credit Card",
      payment_receipt: "123464",
      test_status: "Completed",
    },
    {
      name: "Emma Martinez",
      patient_no: "21",
      patient_contact: "147258",
      patient_type: "OP",
      doctor_name: "Dr. Ravi",
      bill_no: "123465",
      bill_date: "2021-09-10",
      bill_amount: "4500",
      total_amount: "4500",
      payment_status: "Paid",
      payment_date: "2021-09-11",
      payment_mode: "Debit Card",
      payment_receipt: "123465",
      test_status: "Completed",
    },
    {
        name: "Isabella Hernandez",
        patient_no: "22",
        patient_contact: "963852",
        patient_type: "IP",
        doctor_name: "Dr. Anjali",
        bill_no: "123466",
        bill_date: "2021-10-05",
        bill_amount: "6000",
        total_amount: "6000",
        payment_status: "Pending",
        payment_date: "",
        payment_mode: "",
        payment_receipt: "",
        test_status: "Pending",
      },
      {
        name: "Mason Lee",
        patient_no: "23",
        patient_contact: "789456",
        patient_type: "OP",
        doctor_name: "Dr. Arvind",
        bill_no: "123467",
        bill_date: "2021-11-01",
        bill_amount: "2500",
        total_amount: "2500",
        payment_status: "Paid",
        payment_date: "2021-11-02",
        payment_mode: "Net Banking",
        payment_receipt: "123467",
        test_status: "Completed",
      },
      {
        name: "Evelyn King",
        patient_no: "24",
        patient_contact: "159487",
        patient_type: "IP",
        doctor_name: "Dr. Kiran",
        bill_no: "123468",
        bill_date: "2021-11-20",
        bill_amount: "10500",
        total_amount: "10500",
        payment_status: "Pending",
        payment_date: "",
        payment_mode: "",
        payment_receipt: "",
        test_status: "Pending",
      },
      {
        name: "James Walker",
        patient_no: "25",
        patient_contact: "987123",
        patient_type: "OP",
        doctor_name: "Dr. Meera",
        bill_no: "123469",
        bill_date: "2021-12-10",
        bill_amount: "5000",
        total_amount: "5000",
        payment_status: "Paid",
        payment_date: "2021-12-11",
        payment_mode: "Credit Card",
        payment_receipt: "123469",
        test_status: "Completed",
      },
      {
        name: "Lucas Hall",
        patient_no: "26",
        patient_contact: "951753",
        patient_type: "IP",
        doctor_name: "Dr. Vishal",
        bill_no: "123470",
        bill_date: "2021-12-25",
        bill_amount: "8000",
        total_amount: "8000",
        payment_status: "Pending",
        payment_date: "",
        payment_mode: "",
        payment_receipt: "",
        test_status: "Pending",
      },
      {
        name: "Charlotte Scott",
        patient_no: "27",
        patient_contact: "753951",
        patient_type: "OP",
        doctor_name: "Dr. Anuja",
        bill_no: "123471",
        bill_date: "2022-01-05",
        bill_amount: "4000",
        total_amount: "4000",
        payment_status: "Paid",
        payment_date: "2022-01-06",
        payment_mode: "Debit Card",
        payment_receipt: "123471",
        test_status: "Completed",
      },
      {
        name: "Benjamin Young",
        patient_no: "28",
        patient_contact: "852741",
        patient_type: "IP",
        doctor_name: "Dr. Aditya",
        bill_no: "123472",
        bill_date: "2022-02-10",
        bill_amount: "9500",
        total_amount: "9500",
        payment_status: "Paid",
        payment_date: "2022-02-11",
        payment_mode: "Cash",
        payment_receipt: "123472",
        test_status: "Completed",
      },
      {
        name: "Amelia Adams",
        patient_no: "29",
        patient_contact: "654789",
        patient_type: "OP",
        doctor_name: "Dr. Pooja",
        bill_no: "123473",
        bill_date: "2022-03-05",
        bill_amount: "3000",
        total_amount: "3000",
        payment_status: "Paid",
        payment_date: "2022-03-06",
        payment_mode: "Net Banking",
        payment_receipt: "123473",
        test_status: "Completed",
      },
      {
        name: "Ethan Parker",
        patient_no: "30",
        patient_contact: "789321",
        patient_type: "IP",
        doctor_name: "Dr. Shalini",
        bill_no: "123474",
        bill_date: "2022-04-15",
        bill_amount: "7000",
        total_amount: "7000",
        payment_status: "Pending",
        payment_date: "",
        payment_mode: "",
        payment_receipt: "",
        test_status: "Pending",
      },
      {
        name: "Harper Lewis",
        patient_no: "31",
        patient_contact: "123789",
        patient_type: "OP",
        doctor_name: "Dr. Manish",
        bill_no: "123475",
        bill_date: "2022-05-01",
        bill_amount: "5500",
        total_amount: "5500",
        payment_status: "Paid",
        payment_date: "2022-05-02",
        payment_mode: "Credit Card",
        payment_receipt: "123475",
        test_status: "Completed",
      },
  ];
  